require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserFilesController do

  # This should return the minimal set of attributes required to create a valid
  # UserFile. As you add validations to UserFile, be sure to
  # adjust the attributes here as well.
  
  before(:each) do
    s = Dir::pwd.to_s + ("/spec/factories/test.rb")
    @f = Rack::Test::UploadedFile.new(s, "text/x-ruby-script")
  end
  let(:valid_attributes) { { data: @f } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_files as @user_files" do
      user_file = FactoryGirl.create(:user_file)
      get :index, {}, valid_session
      assigns(:user_files).should eq([user_file])
    end
  end

  describe "GET show" do
    it "assigns the requested user_file as @user_file" do
      user_file = FactoryGirl.create(:user_file)
      get :show, {:id => user_file.to_param}, valid_session
      assigns(:user_file).should eq(user_file)
    end
  end

  describe "GET new" do
    it "assigns a new user_file as @user_file" do
      get :new, {}, valid_session
      assigns(:user_file).should be_a_new(UserFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_file as @user_file" do
      user_file = FactoryGirl.create(:user_file)
      get :edit, {:id => user_file.to_param}, valid_session
      assigns(:user_file).should eq(user_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserFile" do
        expect {
          post :create, {:user_file => valid_attributes }, valid_session 
        }.to change(UserFile, :count).by(1)
      end

      it "assigns a newly created user_file as @user_file" do
        post :create, {:user_file => valid_attributes }, valid_session
        
        assigns(:user_file).should be_a(UserFile)
        assigns(:user_file).should be_persisted
      end

      it "redirects to the created user_file" do
        post :create, {:user_file => valid_attributes }, valid_session
        response.should redirect_to(UserFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_file as @user_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserFile.any_instance.stub(:save).and_return(false)
        post :create, {:user_file => valid_attributes }, valid_session
        assigns(:user_file).should be_a_new(UserFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserFile.any_instance.stub(:save).and_return(false)
        post :create, {:user_file => valid_attributes }, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_file" do
        user_file = FactoryGirl.create(:user_file)
        # Assuming there are no other user_files in the database, this
        # specifies that the UserFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        #UserFile.any_instance.should_receive(:save).with({ "name" => "test.rb" })
        put :update, {:id => user_file.to_param, :user_file => valid_attributes }, valid_session
      end

      it "assigns the requested user_file as @user_file" do
        user_file = FactoryGirl.create(:user_file)
        put :update, {:id => user_file.to_param, :user_file => valid_attributes}, valid_session
        assigns(:user_file).should eq(user_file)
      end

      it "redirects to the user_file" do
        user_file = FactoryGirl.create(:user_file)
        put :update, {:id => user_file.to_param, :user_file => valid_attributes}, valid_session
        response.should redirect_to(user_file)
      end
    end

    describe "with invalid params" do
      it "assigns the user_file as @user_file" do
        user_file = FactoryGirl.create(:user_file)
        # Trigger the behavior that occurs when invalid params are submitted
        UserFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_file.to_param, :user_file => valid_attributes }, valid_session
        assigns(:user_file).should eq(user_file)
      end

      it "re-renders the 'edit' template" do
        user_file = FactoryGirl.create(:user_file)
        # Trigger the behavior that occurs when invalid params are submitted
        UserFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_file.to_param, :user_file => valid_attributes }, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_file" do
      user_file = FactoryGirl.create(:user_file)
      expect {
        delete :destroy, {:id => user_file.to_param}, valid_session
      }.to change(UserFile, :count).by(-1)
    end

    it "redirects to the user_files list" do
      user_file = FactoryGirl.create(:user_file)
      delete :destroy, {:id => user_file.to_param}, valid_session
      response.should redirect_to(user_files_url)
    end
  end

  describe "GET download" do
    it "ファイルをダウンロード出来る" do
      user_file = FactoryGirl.build(:user_file)
      user_file.save
      get :download, { :id => user_file.to_param }, valid_session
      #response.should  render_template("show")
      #response.should redirect_to(user_file_url(user_file.id))
    end
  end
end
